import { z } from "npm:zod@4";
import {
  type ApiFormat,
  ApiFormatSchema,
  buildRequest,
  extractContent,
  PERSONA_DIRECTIVES,
  resolveBaseUrl,
  type SkillLevel,
  SkillLevelSchema,
} from "./content_shared.ts";

// ─── Enums ──────────────────────────────────────────────────────────────────

const PracticeReferenceTypeSchema = z.enum([
  "commands",
  "techniques",
  "formulas",
  "none",
]);
type PracticeReferenceType = z.infer<typeof PracticeReferenceTypeSchema>;

const AccessSchema = z.enum(["free", "paywalled"]);
type Access = z.infer<typeof AccessSchema>;

const CourseStatusSchema = z.enum(["draft", "in_review", "published"]);
type CourseStatus = z.infer<typeof CourseStatusSchema>;

// ─── Resource schemas ───────────────────────────────────────────────────────

const CourseSchema = z.object({
  topic: z.string(),
  title: z.string(),
  discipline: z.string(),
  topicSlug: z.string(),
  series: z.string().optional(),
  seriesOrder: z.number().int().positive().optional(),
  prerequisite: z.string().optional(),
  access: AccessSchema,
  language: z.string(),
  status: CourseStatusSchema,
  lastVerified: z.string().optional(),
  sourceVersion: z.string().optional(),
  needsReview: z.boolean(),
  primarySources: z.array(z.string()),
  practiceReferenceType: PracticeReferenceTypeSchema,
  includeExercise: z.boolean(),
  filesWritten: z.array(z.string()),
  model: z.string(),
  generatedAt: z.string(),
});

const DraftSchema = z.object({
  topic: z.string(),
  content: z.string(),
  model: z.string(),
  generatedAt: z.string(),
  warning: z.string(),
});

type ModelContext = {
  globalArgs: {
    apiFormat: ApiFormat;
    apiKey?: string;
    baseUrl?: string;
    outputDir?: string;
  };
  writeResource: (
    specName: "course" | "draft",
    name: string,
    content: unknown,
  ) => Promise<unknown>;
  createFileWriter: (
    specName: "markdown" | "yaml",
    name: string,
  ) => {
    writeText: (text: string) => Promise<unknown>;
  };
  logger: {
    info: (msg: string, props?: Record<string, unknown>) => void;
    error: (msg: string, props?: Record<string, unknown>) => void;
  };
};

// ─── Skeleton ───────────────────────────────────────────────────────────────
// Fixed for every course per the openskills.info create-course playbook.

const SKELETON_FILES = [
  "course.yaml",
  "01-intro.md",
  "02-slides.md",
  "03-cheatsheet.md",
  "04-practice-reference.md",
  "05-quiz.yaml",
  "06-links.yaml",
  "07-video-script.md",
  "08-exercise.md",
  "sources.yaml",
] as const;

const COURSE_MARKER = "generated by @alvagante/content-course";

// ─── Helpers ────────────────────────────────────────────────────────────────

function slugify(input: string): string {
  return input
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Hand-rolled to avoid a YAML dependency: every string scalar goes through
// JSON.stringify, which is also valid YAML flow-scalar syntax (quoted,
// escaped) and safely handles colons/URLs in titles and primary_sources.
function yamlScalar(value: string | number | boolean): string {
  return typeof value === "string" ? JSON.stringify(value) : String(value);
}

function renderCourseYaml(meta: z.infer<typeof CourseSchema>): string {
  const lines: string[] = [
    `# ${COURSE_MARKER} — do not edit by hand`,
    `title: ${yamlScalar(meta.title)}`,
    `discipline: ${yamlScalar(meta.discipline)}`,
    `topic_slug: ${yamlScalar(meta.topicSlug)}`,
  ];
  if (meta.series) lines.push(`series: ${yamlScalar(meta.series)}`);
  if (meta.seriesOrder !== undefined) {
    lines.push(`series_order: ${yamlScalar(meta.seriesOrder)}`);
  }
  if (meta.prerequisite) {
    lines.push(`prerequisite: ${yamlScalar(meta.prerequisite)}`);
  }
  lines.push(`access: ${yamlScalar(meta.access)}`);
  lines.push(`language: ${yamlScalar(meta.language)}`);
  lines.push(`status: ${yamlScalar(meta.status)}`);
  if (meta.lastVerified) {
    lines.push(`last_verified: ${yamlScalar(meta.lastVerified)}`);
  }
  if (meta.sourceVersion) {
    lines.push(`source_version: ${yamlScalar(meta.sourceVersion)}`);
  }
  lines.push(`needs_review: ${yamlScalar(meta.needsReview)}`);
  lines.push(
    `practice_reference_type: ${yamlScalar(meta.practiceReferenceType)}`,
  );
  lines.push(`include_exercise: ${yamlScalar(meta.includeExercise)}`);
  lines.push("primary_sources:");
  for (const source of meta.primarySources) {
    lines.push(`  - ${yamlScalar(source)}`);
  }
  lines.push(`generated_by_model: ${yamlScalar(meta.model)}`);
  lines.push(`generated_at: ${yamlScalar(meta.generatedAt)}`);
  return lines.join("\n") + "\n";
}

function courseDirFor(
  outputDir: string | undefined,
  discipline: string,
  topicSlug: string,
): string {
  const root = outputDir ?? ".";
  return `${root}/courses/${discipline}/${topicSlug}`;
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await Deno.stat(path);
    return true;
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return false;
    throw error;
  }
}

async function listVersionDirs(courseDir: string): Promise<number[]> {
  const versions: number[] = [];
  if (!await pathExists(courseDir)) return versions;

  for await (const entry of Deno.readDir(courseDir)) {
    if (entry.isDirectory && /^[1-9][0-9]*$/.test(entry.name)) {
      versions.push(Number(entry.name));
    }
  }

  return versions.toSorted((a, b) => a - b);
}

// Adopts content-ixen's numeric-version-directory rotation pattern: move the
// existing skeleton into the next version directory before a fresh save, so
// regeneration is never destructive.
async function rotateExistingCourse(
  courseDir: string,
): Promise<{ rotatedVersion?: number; versions: number[] }> {
  await Deno.mkdir(courseDir, { recursive: true });
  const existingVersions = await listVersionDirs(courseDir);
  const coursePath = `${courseDir}/course.yaml`;

  if (!await pathExists(coursePath)) {
    return { versions: existingVersions };
  }

  const yaml = await Deno.readTextFile(coursePath);
  if (!yaml.includes(COURSE_MARKER)) {
    return { versions: existingVersions };
  }

  const rotatedVersion = (existingVersions.at(-1) ?? 0) + 1;
  const targetDir = `${courseDir}/${rotatedVersion}`;
  await Deno.mkdir(targetDir, { recursive: true });

  for (const file of SKELETON_FILES) {
    const sourcePath = `${courseDir}/${file}`;
    if (!await pathExists(sourcePath)) continue;
    await Deno.rename(sourcePath, `${targetDir}/${file}`);
  }

  return {
    rotatedVersion,
    versions: await listVersionDirs(courseDir),
  };
}

type SkeletonFile = {
  filename: typeof SKELETON_FILES[number];
  specName: "markdown" | "yaml";
  instance: string;
  content: string;
};

async function storeCourse(
  context: ModelContext,
  meta: Omit<z.infer<typeof CourseSchema>, "filesWritten">,
  files: SkeletonFile[],
  outputDirOverride?: string,
): Promise<{ dataHandles: unknown[] }> {
  const handles: unknown[] = [];
  const courseDir = courseDirFor(
    outputDirOverride ?? context.globalArgs.outputDir,
    meta.discipline,
    meta.topicSlug,
  );
  await Deno.mkdir(courseDir, { recursive: true });

  const allFiles: SkeletonFile[] = [
    {
      filename: "course.yaml",
      specName: "yaml",
      instance: "course",
      content: renderCourseYaml({ ...meta, filesWritten: [] }),
    },
    ...files,
  ];

  for (const file of allFiles) {
    await Deno.writeTextFile(`${courseDir}/${file.filename}`, file.content);
    const writer = context.createFileWriter(file.specName, file.instance);
    handles.push(await writer.writeText(file.content));
  }

  context.logger.info("Wrote course skeleton to {courseDir}", {
    courseDir,
    files: allFiles.map((f) => f.filename),
  });

  const resourceHandle = await context.writeResource(
    "course",
    `${meta.discipline}-${meta.topicSlug}`,
    { ...meta, filesWritten: allFiles.map((f) => f.filename) },
  );
  handles.push(resourceHandle);

  return { dataHandles: handles };
}

function buildDraftSystemPrompt(skillLevel: SkillLevel): string {
  return `${PERSONA_DIRECTIVES.openskills}

Skill level: ${skillLevel}.

You are producing a rough, UNGROUNDED draft introduction to a technical topic
for an openskills.info mini course. This is scratch material only — no source
grounding, no fact-checking, not suitable for publication. Write 300-600 words
of plain introductory prose: what the topic is, who needs it, and why it
matters. Do not fabricate specific version numbers, dates, or command syntax
you are not confident about; when in doubt, speak in general terms rather than
inventing specifics.`;
}

/**
 * Persists openskills.info mini courses (intro, slides, cheatsheet, quiz,
 * links, video script, optional practice reference and exercise) into
 * courses/<discipline>/<topic-slug>/, per the create-course playbook.
 *
 * `save` is the required path: the calling agent researches primary_sources,
 * drafts and verifies every file, then calls save to persist — keylessly, no
 * LLM call made here. `generate` is a bare, ungrounded single-call draft kept
 * only for parity with the rest of the @alvagante/content-* suite; it is
 * explicitly disqualified for anything claiming accuracy. `prepare` rotates
 * an existing course into a numbered version directory before a refresh, so
 * regeneration is never destructive.
 */
export const model = {
  type: "@alvagante/content-course",
  version: "2026.07.11.1",

  globalArguments: z.object({
    apiFormat: ApiFormatSchema.default("anthropic"),
    apiKey: z.string().optional().meta({ sensitive: true }),
    baseUrl: z.string().url().optional(),
    outputDir: z.string().optional().describe(
      "Catalog root. Courses are written to <outputDir>/courses/<discipline>/<topicSlug>/. Defaults to '.'",
    ),
  }),

  resources: {
    course: {
      description:
        "Course metadata mirroring course.yaml: identity, catalog placement, lifecycle status, and generation provenance.",
      schema: CourseSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    draft: {
      description:
        "Ungrounded draft blob from the parity-only generate method. Never treat as verified course content.",
      schema: DraftSchema,
      lifetime: "infinite" as const,
      garbageCollection: 5,
    },
  },

  files: {
    markdown: {
      description:
        "A course skeleton Markdown file: 01-intro, 02-slides, 03-cheatsheet, 04-practice-reference, 07-video-script, or 08-exercise.",
      contentType: "text/markdown",
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    yaml: {
      description:
        "A course skeleton YAML file: course.yaml, 05-quiz, 06-links, or sources.",
      contentType: "text/yaml",
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
  },

  methods: {
    prepare: {
      description:
        "Prepare a course directory for a new save by moving an existing generated course (course.yaml + its skeleton files) into the next numeric version directory. Call before a regeneration; skip on a first-ever save.",
      arguments: z.object({
        discipline: z.string().min(1),
        topicSlug: z.string().min(1),
        outputDir: z.string().optional(),
        enabled: z.boolean().default(true),
      }),
      execute: async (
        args: {
          discipline: string;
          topicSlug: string;
          outputDir?: string;
          enabled: boolean;
        },
        context: ModelContext,
      ) => {
        if (!args.enabled) return { dataHandles: [] };

        const courseDir = courseDirFor(
          args.outputDir ?? context.globalArgs.outputDir,
          args.discipline,
          args.topicSlug,
        );
        const rotation = await rotateExistingCourse(courseDir);

        if (rotation.rotatedVersion) {
          context.logger.info(
            "Previous course output moved to {courseDir}/{version}",
            { courseDir, version: rotation.rotatedVersion },
          );
        } else {
          context.logger.info(
            "No previous course output found in {courseDir}",
            {
              courseDir,
            },
          );
        }

        return { dataHandles: [] };
      },
    },

    generate: {
      description:
        "Bare LLM call producing a single ungrounded draft blob (no tool grounding, no primary_sources). Exists for suite parity only — DISQUALIFIED for real course content, which must be grounded in cited sources per the create-course playbook. Use save for anything intended for publication.",
      arguments: z.object({
        topic: z.string().min(1),
        details: z.string().optional(),
        skillLevel: SkillLevelSchema.default("intermediate"),
        model: z.string().default("claude-opus-4-8"),
      }),
      execute: async (
        args: {
          topic: string;
          details?: string;
          skillLevel: SkillLevel;
          model: string;
        },
        context: ModelContext,
      ) => {
        const { apiFormat, apiKey, baseUrl: rawBaseUrl } = context.globalArgs;

        if (apiFormat === "anthropic" && !apiKey) {
          throw new Error(
            "apiKey is required when apiFormat is 'anthropic'",
          );
        }

        context.logger.info(
          "Generating ungrounded draft on {topic} — NOT for published content, use save",
          { topic: args.topic, model: args.model },
        );

        const systemPrompt = buildDraftSystemPrompt(args.skillLevel);
        const userMessage = args.details
          ? `Topic: ${args.topic}\n\nAdditional context: ${args.details}`
          : `Topic: ${args.topic}`;
        const baseUrl = resolveBaseUrl(apiFormat, rawBaseUrl);

        const { url, headers, body } = buildRequest(
          apiFormat,
          apiKey,
          baseUrl,
          args.model,
          systemPrompt,
          userMessage,
          4000,
        );

        const response = await fetch(url, {
          method: "POST",
          headers,
          body: JSON.stringify(body),
        });

        if (!response.ok) {
          const errorBody = await response.text();
          throw new Error(
            `Inference API error ${response.status} from ${url}: ${errorBody}`,
          );
        }

        const responseJson = await response.json();
        const { text: content, stopReason } = extractContent(
          apiFormat,
          responseJson,
        );

        if (!content) {
          throw new Error(
            `No text content in API response (stop_reason: ${stopReason})`,
          );
        }

        const draftHandle = await context.writeResource("draft", "draft", {
          topic: args.topic,
          content,
          model: args.model,
          generatedAt: new Date().toISOString(),
          warning:
            "UNVERIFIED — ungrounded bare LLM call, not suitable for published course content. Use save with researched, cited content instead.",
        });

        return { dataHandles: [draftHandle] };
      },
    },

    save: {
      description:
        "Store an agent-written course (researched and verified by the caller) without making any inference call — no API key or endpoint required. The required path per the create-course playbook.",
      arguments: z.object({
        topic: z.string().min(1).describe(
          "The curator-scoped topic, e.g. 'Kubernetes Networking'",
        ),
        discipline: z.string().min(1).describe(
          "Top-level catalog bucket, e.g. 'it', 'business', 'creative'",
        ),
        topicSlug: z.string().min(1).optional().describe(
          "Lowercase, hyphen-separated directory slug. Derived from topic if omitted.",
        ),
        title: z.string().min(1).optional().describe(
          "Display title for course.yaml. Defaults to topic.",
        ),
        primarySources: z.array(z.string().min(1)).min(1).describe(
          "Official docs/homepage URL(s) backing this course. Required — generation does not proceed on a bare topic name with zero seeding.",
        ),
        series: z.string().min(1).optional(),
        seriesOrder: z.number().int().positive().optional(),
        prerequisite: z.string().min(1).optional(),
        access: AccessSchema.default("free"),
        language: z.string().min(1).default("en"),
        status: CourseStatusSchema.default("in_review"),
        humanApproved: z.boolean().default(false).describe(
          "Must be true to save with status=published. Mandatory human review gate — ignored for draft/in_review.",
        ),
        lastVerified: z.string().optional(),
        sourceVersion: z.string().optional(),
        needsReview: z.boolean().default(false),
        practiceReferenceType: PracticeReferenceTypeSchema.default("none"),
        includeExercise: z.boolean().default(false),
        introContent: z.string().min(1).describe(
          "01-intro.md: beginner intro, what/who/why, with an embedded '## Glossary' section.",
        ),
        slidesContent: z.string().min(1).describe(
          "02-slides.md: Marp/reveal-style deck source.",
        ),
        cheatsheetContent: z.string().min(1).describe(
          "03-cheatsheet.md: dense core-concepts sheet, e.g. from content-cheatsheet's markdown output.",
        ),
        practiceReferenceContent: z.string().min(1).optional().describe(
          "04-practice-reference.md: commands/config/techniques with an embedded '## Common Pitfalls' section. Required when practiceReferenceType != 'none'.",
        ),
        quizContent: z.string().min(1).describe(
          "05-quiz.yaml: MCQ + explanation, tiered beginner→intermediate→hero.",
        ),
        linksContent: z.string().min(1).describe(
          "06-links.yaml: seeded from primarySources plus AI-supplemented links, incl. where-to-go-next pointers.",
        ),
        videoScriptContent: z.string().min(1).describe(
          "07-video-script.md: TTS-narrated-slides script.",
        ),
        exerciseContent: z.string().min(1).optional().describe(
          "08-exercise.md: hands-on lab. Required when includeExercise is true.",
        ),
        sourcesContent: z.string().min(1).describe(
          "sources.yaml: citations backing every factual claim, incl. quiz answers and image artifacts.",
        ),
        model: z.string().default("external").describe(
          "Identifier of whatever produced the content",
        ),
        outputDir: z.string().optional().describe(
          "Override the global outputDir for this run",
        ),
      }).superRefine((args, ctx) => {
        if (args.includeExercise && args.practiceReferenceType === "none") {
          ctx.addIssue({
            code: "custom",
            path: ["includeExercise"],
            message:
              "includeExercise requires practiceReferenceType != 'none' — there's nothing practical to build a hands-on lab out of otherwise.",
          });
        }
        if (
          args.practiceReferenceType !== "none" &&
          !args.practiceReferenceContent
        ) {
          ctx.addIssue({
            code: "custom",
            path: ["practiceReferenceContent"],
            message:
              "practiceReferenceContent is required when practiceReferenceType != 'none'.",
          });
        }
        if (args.includeExercise && !args.exerciseContent) {
          ctx.addIssue({
            code: "custom",
            path: ["exerciseContent"],
            message:
              "exerciseContent is required when includeExercise is true.",
          });
        }
        if (args.status === "published" && !args.humanApproved) {
          ctx.addIssue({
            code: "custom",
            path: ["humanApproved"],
            message:
              "status=published requires humanApproved=true — the human review gate is mandatory, not optional.",
          });
        }
      }),
      execute: async (
        args: {
          topic: string;
          discipline: string;
          topicSlug?: string;
          title?: string;
          primarySources: string[];
          series?: string;
          seriesOrder?: number;
          prerequisite?: string;
          access: Access;
          language: string;
          status: CourseStatus;
          humanApproved: boolean;
          lastVerified?: string;
          sourceVersion?: string;
          needsReview: boolean;
          practiceReferenceType: PracticeReferenceType;
          includeExercise: boolean;
          introContent: string;
          slidesContent: string;
          cheatsheetContent: string;
          practiceReferenceContent?: string;
          quizContent: string;
          linksContent: string;
          videoScriptContent: string;
          exerciseContent?: string;
          sourcesContent: string;
          model: string;
          outputDir?: string;
        },
        context: ModelContext,
      ) => {
        const topicSlug = args.topicSlug ?? slugify(args.topic);
        const title = args.title ?? args.topic;

        if (!args.introContent.includes("## Glossary")) {
          context.logger.info(
            "01-intro.md has no '## Glossary' section — the skeleton expects one embedded",
            { topic: args.topic },
          );
        }
        if (
          args.practiceReferenceContent &&
          !args.practiceReferenceContent.includes("## Common Pitfalls")
        ) {
          context.logger.info(
            "04-practice-reference.md has no '## Common Pitfalls' section — the skeleton expects one embedded",
            { topic: args.topic },
          );
        }

        context.logger.info(
          "Saving course on {topic} to {discipline}/{topicSlug}",
          {
            topic: args.topic,
            discipline: args.discipline,
            topicSlug,
            status: args.status,
          },
        );

        const files: SkeletonFile[] = [
          {
            filename: "01-intro.md",
            specName: "markdown",
            instance: "01-intro",
            content: args.introContent,
          },
          {
            filename: "02-slides.md",
            specName: "markdown",
            instance: "02-slides",
            content: args.slidesContent,
          },
          {
            filename: "03-cheatsheet.md",
            specName: "markdown",
            instance: "03-cheatsheet",
            content: args.cheatsheetContent,
          },
          {
            filename: "05-quiz.yaml",
            specName: "yaml",
            instance: "05-quiz",
            content: args.quizContent,
          },
          {
            filename: "06-links.yaml",
            specName: "yaml",
            instance: "06-links",
            content: args.linksContent,
          },
          {
            filename: "07-video-script.md",
            specName: "markdown",
            instance: "07-video-script",
            content: args.videoScriptContent,
          },
          {
            filename: "sources.yaml",
            specName: "yaml",
            instance: "sources",
            content: args.sourcesContent,
          },
        ];

        if (
          args.practiceReferenceType !== "none" &&
          args.practiceReferenceContent
        ) {
          files.push({
            filename: "04-practice-reference.md",
            specName: "markdown",
            instance: "04-practice-reference",
            content: args.practiceReferenceContent,
          });
        }

        if (args.includeExercise && args.exerciseContent) {
          files.push({
            filename: "08-exercise.md",
            specName: "markdown",
            instance: "08-exercise",
            content: args.exerciseContent,
          });
        }

        return await storeCourse(
          context,
          {
            topic: args.topic,
            title,
            discipline: args.discipline,
            topicSlug,
            series: args.series,
            seriesOrder: args.seriesOrder,
            prerequisite: args.prerequisite,
            access: args.access,
            language: args.language,
            status: args.status,
            lastVerified: args.lastVerified,
            sourceVersion: args.sourceVersion,
            needsReview: args.needsReview,
            primarySources: args.primarySources,
            practiceReferenceType: args.practiceReferenceType,
            includeExercise: args.includeExercise,
            model: args.model,
            generatedAt: new Date().toISOString(),
          },
          files,
          args.outputDir,
        );
      },
    },
  },
};
