import { model } from "./content_course.ts";

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function stubContext(overrides?: { apiKey?: string }) {
  const writes: Array<{ specName: string; instance: string; text: string }> = [];
  const resources: unknown[] = [];
  const logs: string[] = [];
  const context = {
    globalArgs: { apiFormat: "anthropic" as const, apiKey: overrides?.apiKey },
    writeResource: (specName: string, name: string, content: unknown) => {
      resources.push(content);
      return Promise.resolve({ specName, name });
    },
    createFileWriter: (specName: string, instance: string) => ({
      writeText: (text: string) => {
        writes.push({ specName, instance, text });
        return Promise.resolve({});
      },
    }),
    logger: {
      info: (msg: string) => {
        logs.push(msg);
      },
      error: (msg: string) => {
        logs.push(msg);
      },
    },
  };
  return { context, writes, resources, logs };
}

const MINIMAL_SAVE_ARGS = {
  topic: "Kubernetes: Networking",
  discipline: "it",
  primarySources: ["https://kubernetes.io/docs/concepts/services-networking/"],
  introContent: "# Intro\n\n## Glossary\n\n- Pod: a group of containers.",
  slidesContent: "# Slide 1\n---\n# Slide 2",
  cheatsheetContent: "# Cheatsheet\n\n- kubectl get svc",
  quizContent: "questions: []",
  linksContent: "links: []",
  videoScriptContent: "Welcome to the course.",
  sourcesContent: "sources: []",
};

Deno.test("save schema rejects includeExercise without a practiceReferenceType", () => {
  const result = model.methods.save.arguments.safeParse({
    ...MINIMAL_SAVE_ARGS,
    includeExercise: true,
  });
  assert(!result.success, "expected schema validation to fail");
});

Deno.test("save schema rejects a practiceReferenceType without practiceReferenceContent", () => {
  const result = model.methods.save.arguments.safeParse({
    ...MINIMAL_SAVE_ARGS,
    practiceReferenceType: "commands",
  });
  assert(!result.success, "expected schema validation to fail");
});

Deno.test("save schema rejects status=published without humanApproved", () => {
  const rejected = model.methods.save.arguments.safeParse({
    ...MINIMAL_SAVE_ARGS,
    status: "published",
  });
  assert(!rejected.success, "expected publish without approval to fail");

  const accepted = model.methods.save.arguments.safeParse({
    ...MINIMAL_SAVE_ARGS,
    status: "published",
    humanApproved: true,
  });
  assert(accepted.success, "expected publish with approval to pass");
});

Deno.test("save writes the fixed skeleton, derives a slug, and quotes course.yaml safely", async () => {
  const outputDir = await Deno.makeTempDir({ prefix: "content-course-" });
  const { context, writes } = stubContext();

  const parsed = model.methods.save.arguments.parse({
    ...MINIMAL_SAVE_ARGS,
    outputDir,
  });
  await model.methods.save.execute(parsed, context);

  const courseDir = `${outputDir}/courses/it/kubernetes-networking`;
  const courseYaml = await Deno.readTextFile(`${courseDir}/course.yaml`);

  assert(
    courseYaml.includes('title: "Kubernetes: Networking"'),
    "expected the colon-bearing title to be JSON-quoted, not break YAML parsing",
  );
  assert(
    courseYaml.includes(
      '  - "https://kubernetes.io/docs/concepts/services-networking/"',
    ),
    "expected the primary source URL to be quoted under primary_sources",
  );
  assert(
    courseYaml.includes("generated by @alvagante/content-course"),
    "expected the ownership marker used by prepare's rotation check",
  );

  for (
    const filename of [
      "01-intro.md",
      "02-slides.md",
      "03-cheatsheet.md",
      "05-quiz.yaml",
      "06-links.yaml",
      "07-video-script.md",
      "sources.yaml",
    ]
  ) {
    assert(
      await Deno.stat(`${courseDir}/${filename}`).then(() => true).catch(() =>
        false
      ),
      `expected ${filename} to be written to disk`,
    );
  }
  assert(
    !await Deno.stat(`${courseDir}/04-practice-reference.md`).then(() => true)
      .catch(() => false),
    "did not request a practice reference, so it should not be written",
  );

  assert(
    writes.some((w) => w.specName === "yaml" && w.instance === "course"),
    "expected a tracked yaml/course file artifact",
  );
  assert(
    writes.some((w) => w.specName === "markdown" && w.instance === "01-intro"),
    "expected a tracked markdown/01-intro file artifact",
  );
});

Deno.test("prepare rotates an existing generated course into a numbered version directory", async () => {
  const outputDir = await Deno.makeTempDir({ prefix: "content-course-" });
  const { context } = stubContext();

  await model.methods.save.execute(
    model.methods.save.arguments.parse({ ...MINIMAL_SAVE_ARGS, outputDir }),
    context,
  );

  await model.methods.prepare.execute(
    { discipline: "it", topicSlug: "kubernetes-networking", outputDir, enabled: true },
    context,
  );

  const courseDir = `${outputDir}/courses/it/kubernetes-networking`;
  const rotated = await Deno.readTextFile(`${courseDir}/1/course.yaml`);
  assert(
    rotated.includes("generated by @alvagante/content-course"),
    "expected the previous course.yaml to be moved into version directory 1",
  );

  const currentExists = await Deno.stat(`${courseDir}/course.yaml`).then(() =>
    true
  ).catch(() => false);
  assert(
    !currentExists,
    "expected the current course.yaml to have been moved, not copied",
  );
});

Deno.test("prepare does not rotate a directory it does not own", async () => {
  const outputDir = await Deno.makeTempDir({ prefix: "content-course-" });
  const courseDir = `${outputDir}/courses/it/foreign`;
  await Deno.mkdir(courseDir, { recursive: true });
  await Deno.writeTextFile(`${courseDir}/course.yaml`, "title: unrelated file\n");

  const { context } = stubContext();
  await model.methods.prepare.execute(
    { discipline: "it", topicSlug: "foreign", outputDir, enabled: true },
    context,
  );

  const stillThere = await Deno.readTextFile(`${courseDir}/course.yaml`);
  assert(
    stillThere === "title: unrelated file\n",
    "expected an unmarked course.yaml to be left untouched",
  );
});

Deno.test("generate requires an apiKey under anthropic apiFormat", async () => {
  const { context } = stubContext({ apiKey: undefined });
  await assertRejects(
    () =>
      model.methods.generate.execute(
        { topic: "Kubernetes Networking", skillLevel: "intermediate", model: "claude-opus-4-8" },
        context,
      ),
    "apiKey is required",
  );
});

async function assertRejects(
  fn: () => Promise<unknown>,
  messageIncludes: string,
): Promise<void> {
  try {
    await fn();
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    assert(
      message.includes(messageIncludes),
      `expected error message to include "${messageIncludes}", got: ${message}`,
    );
    return;
  }
  throw new Error("expected function to throw, but it did not");
}
